/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import PackConexion.Conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class appLuz extends javax.swing.JFrame {
   DefaultTableModel model;
   /**
    * Creates new form appLuz
    */
   public appLuz() {
      initComponents();
      String[] titulos = new String[] {"Codigo Postal", "Estado", "Municipio","Colonia","Calle","Fecha de Instalacion","Tipo de Lampara", "Potencia W","Hora E","Hora A","Foto","Semaforo"
             ,"Feche Censo","DMS", "DMM", "DD","Vida x Hora", "Eficicencia Luminosa"};
    model = new DefaultTableModel(null,titulos);
    Tb_Princi.setModel(model);
      
      centrar();
      mostrarDatos();
      
   }
   public void centrar(){
      setLocationRelativeTo(null);
   }
   
   public void mostrarDatos(){
      while(model.getRowCount()>0){
               model.removeRow(0);
            }
        Conexion objConexion = new Conexion();
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM principal");
            while(resultado.next()){
//                System.out.println(resultado.getString("ID"));
//                System.out.println(resultado.getString("Nombre"));
//                System.out.println(resultado.getString("Correo"));
//                Object[] oUsuario = new Object[]{resultado.getString("ID"),resultado.getString("Nombre"),resultado.getString("Correo")};
                  Object[] oUsuario = new Object[]{resultado.getString("CodigoPostal"),resultado.getString("Estado"),resultado.getString("Municipio"),resultado.getString("Colonia"),
                  resultado.getString("Calle"),resultado.getString("FechaInstalacion"),resultado.getString("TipoLampara"),resultado.getString("PotenciaW"),resultado.getString("HoraEncendido")
                  ,resultado.getString("HoraApagado"),resultado.getString("Imagen"),resultado.getString("Semaforo"),resultado.getString("FechaCenso"),resultado.getString("DMS"),resultado.getString("DMM")
                  ,resultado.getString("DD"),resultado.getString("VidaMediaH"),resultado.getString("EficaciaLum")};
                model.addRow(oUsuario);
               }
            } catch (Exception e) {
               System.out.println(e);
            }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      Tb_Princi = new javax.swing.JTable();
      CB_estado = new javax.swing.JComboBox<>();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      CB_muni = new javax.swing.JComboBox<>();
      jLabel6 = new javax.swing.JLabel();
      CB_Col = new javax.swing.JComboBox<>();
      jLabel7 = new javax.swing.JLabel();
      CB_Calle = new javax.swing.JComboBox<>();
      jLabel8 = new javax.swing.JLabel();
      CB_TipoLam = new javax.swing.JComboBox<>();
      txt_editar = new javax.swing.JButton();
      bt_nuevo = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cfe2.png"))); // NOI18N
      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 130));

      jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
      jLabel2.setText("SISTEMA DE ALUMBRADO");
      getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 510, 40));
      getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 80, 20));

      Tb_Princi.setAutoCreateRowSorter(true);
      Tb_Princi.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane1.setViewportView(Tb_Princi);

      getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1070, 320));

      CB_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - - - - - -", "Puebla", " " }));
      getContentPane().add(CB_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, -1));

      jLabel4.setText("ESTADO");
      getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

      jLabel5.setText("MUNICIPIO");
      getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

      CB_muni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - - - - - -", "Teziutlan ", "Hueytamalco" }));
      getContentPane().add(CB_muni, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 130, -1));

      jLabel6.setText("COLONIA");
      getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

      CB_Col.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - - - - - -", "Centro" }));
      getContentPane().add(CB_Col, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 160, -1));

      jLabel7.setText("CALLE");
      getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

      CB_Calle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - - - - - -", "Allende", "Francisco Sarabia", " " }));
      getContentPane().add(CB_Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 160, -1));

      jLabel8.setText("TIPO DE LAMPARA");
      getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

      CB_TipoLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - - - - - -", "LED" }));
      getContentPane().add(CB_TipoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

      txt_editar.setText("EDITAR");
      getContentPane().add(txt_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 100, 30));

      bt_nuevo.setText("AGREGAR");
      bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            bt_nuevoActionPerformed(evt);
         }
      });
      getContentPane().add(bt_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 210, 110, 30));

      jButton1.setText("BORRAR");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 120, 30));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
      try {
         Incert ince = new Incert();
      this.setVisible(false);
      ince.setVisible(true);
      } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane,e);
      }
      
   }//GEN-LAST:event_bt_nuevoActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Conexion con = new Conexion();
     //PaSG sg = recuperar
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(appLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(appLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(appLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(appLuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new appLuz().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> CB_Calle;
   private javax.swing.JComboBox<String> CB_Col;
   private javax.swing.JComboBox<String> CB_TipoLam;
   private javax.swing.JComboBox<String> CB_estado;
   private javax.swing.JComboBox<String> CB_muni;
   private javax.swing.JTable Tb_Princi;
   private javax.swing.JButton bt_nuevo;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton txt_editar;
   // End of variables declaration//GEN-END:variables
}
