/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;

import PackConexion.Conexion;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Incert extends javax.swing.JFrame {

   /**
    * Creates new form Incert
    */
   public Incert() {
      initComponents();
      centrar();
   }
   
   public void centrar(){
      setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      bt_GC = new javax.swing.JButton();
      jb_limpiar = new javax.swing.JButton();
      jb_agregar = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      txt_cp = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txt_estado = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txt_minicipio = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txt_colonia = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      txt_calle = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      txt_fechaInsta = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      txt_tipo = new javax.swing.JTextField();
      jLabel10 = new javax.swing.JLabel();
      txt_poteW = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      txt_horaE = new javax.swing.JTextField();
      jLabel12 = new javax.swing.JLabel();
      txt_horaA = new javax.swing.JTextField();
      lbl_img = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      txt_semaforo = new javax.swing.JTextField();
      jLabel15 = new javax.swing.JLabel();
      txt_fechaUltimo = new javax.swing.JTextField();
      jLabel16 = new javax.swing.JLabel();
      txt_dms = new javax.swing.JTextField();
      jLabel17 = new javax.swing.JLabel();
      txt_dmm = new javax.swing.JTextField();
      jLabel18 = new javax.swing.JLabel();
      txt_dd = new javax.swing.JTextField();
      jLabel19 = new javax.swing.JLabel();
      txt_vidaM = new javax.swing.JTextField();
      jLabel20 = new javax.swing.JLabel();
      txt_Efica = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();
      bt_imagen = new javax.swing.JButton();
      lbl_nomImg = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(1000, 500));
      setPreferredSize(new java.awt.Dimension(1100, 500));
      setResizable(false);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel1.setText("AGREGAR");
      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/computadora.png"))); // NOI18N
      getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

      bt_GC.setText("GUARDAR CAMBIOS");
      getContentPane().add(bt_GC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

      jb_limpiar.setText("LIMPIAR");
      jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jb_limpiarActionPerformed(evt);
         }
      });
      getContentPane().add(jb_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, -1, -1));

      jb_agregar.setText("AGREGAR");
      jb_agregar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jb_agregarActionPerformed(evt);
         }
      });
      getContentPane().add(jb_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

      jLabel3.setText("Codigo Postal");
      getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
      getContentPane().add(txt_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, -1));

      jLabel4.setText("Estado");
      getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));
      getContentPane().add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, -1));

      jLabel5.setText("Municipio");
      getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));
      getContentPane().add(txt_minicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 130, -1));

      jLabel6.setText("Colonia");
      getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));
      getContentPane().add(txt_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 130, -1));

      jLabel7.setText("Calle");
      getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));
      getContentPane().add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 120, -1));

      jLabel8.setText("Fecha de Instalación");
      getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));
      getContentPane().add(txt_fechaInsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 110, -1));

      jLabel9.setText("Tipo de Lampara");
      getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
      getContentPane().add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

      jLabel10.setText("Potencia W");
      getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));
      getContentPane().add(txt_poteW, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, -1));

      jLabel11.setText("Hora de Encendido");
      getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));
      getContentPane().add(txt_horaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 110, -1));

      jLabel12.setText("Hora de Apagado");
      getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));
      getContentPane().add(txt_horaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 90, -1));
      getContentPane().add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 130, 120));

      jLabel14.setText("Semaforo");
      getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));
      getContentPane().add(txt_semaforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 110, -1));

      jLabel15.setText("Fecha de ultimo Censo");
      getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
      getContentPane().add(txt_fechaUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, -1));

      jLabel16.setText("DMS");
      getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));
      getContentPane().add(txt_dms, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 190, -1));

      jLabel17.setText("DMM");
      getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));
      getContentPane().add(txt_dmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 160, -1));

      jLabel18.setText("DD");
      getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));
      getContentPane().add(txt_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 110, -1));

      jLabel19.setText("Vida Media");
      getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));
      getContentPane().add(txt_vidaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 110, -1));

      jLabel20.setText("Eficacia Luminosa");
      getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, -1, -1));
      getContentPane().add(txt_Efica, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 100, -1));

      jButton1.setBackground(new java.awt.Color(204, 204, 255));
      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/casa-icono-silueta.png"))); // NOI18N
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 80, 70));

      bt_imagen.setText("Seleccionar imagen");
      bt_imagen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            bt_imagenActionPerformed(evt);
         }
      });
      getContentPane().add(bt_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, -1, 30));

      lbl_nomImg.setText("-  -  -  -  -  -  -  -  -  -  -  -  -");
      getContentPane().add(lbl_nomImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 300, 20));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jb_limpiarActionPerformed

   private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
     
      try {
         Conexion con = new Conexion();
    String codigo = txt_cp.getText();
    String estado = txt_estado.getText();
    String mini = txt_minicipio.getText();
    String colo = txt_colonia.getText();
    String calle = txt_calle.getText();
    String fechaCre = txt_fechaInsta.getText();
    String tipoL = txt_tipo.getText();
    String pote = txt_poteW.getText();
    String horaE = txt_horaE.getText();
    String horaA = txt_horaA.getText();
    FileInputStream arcfo = new FileInputStream(lbl_nomImg.getText());
    String sema = txt_semaforo.getText();
    String fechaU = txt_fechaUltimo.getText();
    String dms = txt_dms.getText();
    String dmm = txt_dmm.getText();
    String dd = txt_dd.getText();
    String vidaMH = txt_vidaM.getText();
    String efiLum = txt_Efica.getText();
         con.ejecutarSentenciaSQL("INSERT INTO principal(CodigoPostal, Estado, Municipio, Colonia,"
    + "Calle, FechaInstalacion, TipoLampara, PotenciaW, HoraEncendido, HoraApagado, Imagen, Semaforo,"
    + "FechaCenso, DMS, DMM, DD, VidaMediaH, EficaciaLum) VALUES ('"+codigo+"','"+estado+"','"+mini+"','"+colo+
      "','"+calle+"','"+fechaCre+"','"+tipoL+"','"+pote+"','"+horaE+"','"+horaA+"','"+arcfo+"','"+sema+"','"+fechaU+"','"+dms+"','"+dmm+
      "','"+dd+"','"+vidaMH+"','"+efiLum+"')");
         JOptionPane.showMessageDialog(null,"Agregado con exito");
      } catch (Exception e) {
         System.out.println(e);
      }
    
    
   }//GEN-LAST:event_jb_agregarActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
         appLuz luz = new appLuz();
         this.setVisible(false);
         luz.setVisible(true);
      } catch (Exception e) {
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void bt_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imagenActionPerformed
     JFileChooser ima = new JFileChooser();
     int ventana = ima.showOpenDialog(null);
      if (ventana == JFileChooser.APPROVE_OPTION) {
         File fi = ima.getSelectedFile();
         lbl_nomImg.setText(String.valueOf(fi));
         Image fo = getToolkit().getImage(lbl_nomImg.getText());
         fo = fo.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
         lbl_img.setIcon(new ImageIcon(fo));
      } else {
      }
            
   }//GEN-LAST:event_bt_imagenActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Incert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Incert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Incert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Incert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Incert().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bt_GC;
   private javax.swing.JButton bt_imagen;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JButton jb_agregar;
   private javax.swing.JButton jb_limpiar;
   private javax.swing.JLabel lbl_img;
   private javax.swing.JLabel lbl_nomImg;
   private javax.swing.JTextField txt_Efica;
   private javax.swing.JTextField txt_calle;
   private javax.swing.JTextField txt_colonia;
   private javax.swing.JTextField txt_cp;
   private javax.swing.JTextField txt_dd;
   private javax.swing.JTextField txt_dmm;
   private javax.swing.JTextField txt_dms;
   private javax.swing.JTextField txt_estado;
   private javax.swing.JTextField txt_fechaInsta;
   private javax.swing.JTextField txt_fechaUltimo;
   private javax.swing.JTextField txt_horaA;
   private javax.swing.JTextField txt_horaE;
   private javax.swing.JTextField txt_minicipio;
   private javax.swing.JTextField txt_poteW;
   private javax.swing.JTextField txt_semaforo;
   private javax.swing.JTextField txt_tipo;
   private javax.swing.JTextField txt_vidaM;
   // End of variables declaration//GEN-END:variables
}
